### ISSUE TITLE
Hierarchical Notes

### ISSUE THREAD

**Issue by strider72** [estep248/Pocket-Plan#10]
It would be a huge boost to flexibility if we could make notes subsidiary to other notes. We could then use the app in a lot of different ways — from a flat notes list to a basic outliner program.  In some uses I imagine not even entering note text but just using the titles as list entries.

**Comment by JakeGonder** [comment]
Added option to create folders, that are simply a note consisting of a title, which can contain more folders or notes on the Beta branch
