### ISSUE TITLE
Notes: set default note color (or rotate/random options)

### ISSUE THREAD

**Issue by strider72** [estep248/Pocket-Plan#13]
What it says on the title. Give us an option to choose default note color! :-)

ALSO: I might suggest making the colors a bit more faded, and using black text.

**Comment by JakeGonder** [comment]
How about instead of default, remember the last choice?

**Comment by JakeGonder** [comment]
Added the randomize feature on the beta branch.

**Comment by strider72** [comment]
Random should be an option, but the colors can definitely be used for more than mere aesthetics.  Are you also implementing the "remember last used" idea? It was a good one!

**Comment by strider72** [comment]
> How about instead of default, remember the last choice?

This ^^

**Comment by JakeGonder** [comment]
Alright, gonna make it optional and add the last used option, see newest issue
