### ISSUE TITLE
Keep shopping list group order

### ISSUE THREAD

**Issue by strider72** [estep248/Pocket-Plan#15]
*What happens now*:  
I have shopping list items in three categories: Cat A, Cat B, and Cat C.  (Kat von D was not available for testing).  I have the category groups in that order.

I check off everything in Cat B. Cat B group turns grey and drops to bottom of the list.

I add something to Cat B. Cat B gets its color back, but remains at the bottom of the group list.

*What should happen*:  
When I add something to the empty Cat B, it should return to its position in the group order.

**Comment by estep248** [comment]
I have implemented your request, it will be available in the next app update.

Thanks for your suggestion!
