### ISSUE TITLE
Remove sleep notification after 5 hours or so

### ISSUE THREAD

**Issue by JakeGonder** [estep248/Pocket-Plan#19]

**Comment by strider72** [comment]
Heh. I had an app called Go To Sleep, that would do what you feature does. Problem is it wouldn't recognize that I'd stopped using my phone, so all the next day it's yelling at me "Why are you still up? It's 648 minutes past your bedtime!" ;-)

**Comment by estep248** [comment]
implemented in release 1.3.2
