### ISSUE TITLE
Text in settings is not in English

### ISSUE THREAD

**Issue by qsyntrax** [estep248/Pocket-Plan#24]
This text is not in English
![image21](https://user-images.githubusercontent.com/96214827/149893049-5eb14bff-a55d-4217-95d6-5304dcd4f52f.png)

**Comment by JakeGonder** [comment]
Fixed it, thanks for letting us know.
Just curious, since we had an inexplicable increase in users today and this is your first issue, how did you find out about our app?

**Comment by qsyntrax** [comment]
This post
https://www.reddit.com/r/androidapps/comments/rzhhed/i_created_an_open_source_doeverything_app/

**Comment by JakeGonder** [comment]
Alright, thanks a lot!
