### ISSUE TITLE
Language bug

### ISSUE THREAD

**Issue by BluePixel4k** [estep248/Pocket-Plan#25]
There is a language bug. If the system language is English and you change the app language to German (Settings > General > Language > German). Than you add an item to the shopping list, the suggestions are right, but the category is in English, not in German.

![Screenshot_Bread](https://user-images.githubusercontent.com/77979781/152575090-80ab5369-4d0f-41aa-a284-39d24739ee3c.png)

**Comment by JakeGonder** [comment]
So far I could not reproduce your bug (see video), can you be more specific? You said
`change the app language to German`
but your screenshot shows only english strings (e.g. the "No important tasks" in the background and the "Add" and "Cancel" button etc.), is this what your app looked like once you selected "german"?

https://user-images.githubusercontent.com/51212295/152588612-ff074736-e70c-40b2-b93c-b1d07068cb48.mp4

**Comment by BluePixel4k** [comment]
Strange, I have the same settings. But for me, the app does not properly jump over to German.
The option "Reset all settings to default" also has no effect on the set language.  

![Screenshot_20220204-202930](https://user-images.githubusercontent.com/77979781/152592462-05076e0d-9f0a-4823-92a7-4091242b95d6.png)

![Screenshot_20220204-202950](https://user-images.githubusercontent.com/77979781/152592490-d17777ed-1d4e-4b71-b39b-8938f4212e87.png)

![Screenshot_20220204-203256](https://user-images.githubusercontent.com/77979781/152592517-65398557-34a5-489b-b45a-c1ea2bdd7321.png)

**Comment by JakeGonder** [comment]
Thats really odd, does this problem still stay when you exit the app, close it completely and restart it? Also what device / android verison are you on?

**Comment by BluePixel4k** [comment]
Yes, the problem still remains.
I just reset the app again as well, but to no avail.

Device: Google Pixel 5
OS: Android 12 - GrapheneOS

**Comment by JakeGonder** [comment]
You were right, this is an initialization bug that we already fixed on the Beta branch in [this commit](https://github.com/estep248/Pocket-Plan/commit/0038a6c40eb54e925dd680ce81649abce7b341eb#diff-5726aef1fe71c1571755feb1ae9f00d1885a8fdfe32e71cd526ca9f2c24ec05d) I just forgot about it, thanks for letting us know tho, it should be fixed in 1.4, if not let us know

**Comment by JakeGonder** [comment]
I found the source of this bug now, it had something to do with how gradle handles multiple languages.
The bug fix is included in Release 1.3.3 which should go live in a few hours, once you update your app, please let us know if the problem is resolved.

**Comment by BluePixel4k** [comment]
Thanks, with the v1.3.3 the bug is now solved.
