### ISSUE TITLE
[enhancement] Some ideas for improvements

### ISSUE THREAD

**Issue by tcgmoo** [estep248/Pocket-Plan#7]
## General

Add to F-Droid

## Notes

1. Add an archive for notes
2. Add checklists
3. Allow editing notes using Markdown
4. Make notes look like how they do in screenshots: the whole box colored, not just the text. Same for to-do list

## To-Do list

1. Add sub-tasks to to-do lists. You can have the whole task be of the same priority, or give each sub-task be a different priority within the task
2. Allow adding deadlines for tasks

**Comment by JakeGonder** [comment]
> Add to F-Droid 

Added this to our todo list

>Add an archive for notes

Could you be more specific on what you mean by that? An archive that saves deleted notes?

>Allow editing notes using Markdown

We will add this as an optional todo, and see if its a feature requested by more users.

>Make Make notes look like how they do in screenshots.

We adjusted the dark theme but did not update the screenshots in playstore yet. If you think the older design looks better, we can consider making it optional in the settings.

>Add sub-tasks to to-do lists

Added this to our todo list

>Allow adding deadlines for tasks

Added this to our todo list

**Comment by tcgmoo** [comment]
> Could you be more specific on what you mean by that? An archive that saves deleted notes?

Not exactly. You can have a place for deleted notes too, but an archive could be used to store old notes that you don't want to delete but don't want taking up space in your main notes screen.

> We adjusted the dark theme but did not update the screenshots in playstore yet. If you think the older design looks better, we can consider making it optional in the settings.

Please do. I'm sure there's people who like the new design too, so making it optional sounds perfect.

**Comment by JakeGonder** [comment]
Alright, we will implement both!

**Comment by JakeGonder** [comment]
We added the new design option feature on the beta branch. I split your other recommendations into multiple new issues, to improve readibility, which is why this issue can be closed.

**Comment by JakeGonder** [comment]
> Make notes look like how they do in screenshots: the whole box colored, not just the text. Same for to-do list
@tcgmoo Since v1.3.3 which is now live, you can swap back to the legacy design, in settings => appearance (only in dark theme)

**Comment by tcgmoo** [comment]
Yes, I noticed, and it's perfect. Thank you!
